### PR TITLE
bug(ConsoleReporter): fix a bug in the console reporter where no options were passed

### PR DESCRIPTION
**Pull request by iammerrick**
Some of these things, it seems non-sensible to do a pull request... The real request here is this.... Will you trust me @IgorMinar?

### CODE REVIEW

**Comment by IgorMinar** [comment]
in commit message: `bug` -> `fix`

I will trust you, but let's get a few PRs in with a review first. All of my PRs are reviewed by someone else. Code reviews are not about distrust, but about sharing and learning.

**Comment by IgorMinar** [comment]
Can you write a test for this please?

Otherwise LGTM

**Comment by iammerrick** [comment]
Lesson learned, what a terrible time to actually not have a spec. :-P Alright changes the wording and squashed the commits in a new one.

**Comment by IgorMinar** [comment]
Lgtm

**Pull request merged**
